name: QonexAI Flight Report ✈️

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:

jobs:
  flight_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QuantumTrader-AI
        uses: actions/checkout@v4

      - name: Generate System Flight Log
        run: |
          echo "🧭 QonexAI Flight Report - $(date)" > flight_report.txt
          echo "--------------------------------------" >> flight_report.txt
          echo "🚀 Repo: QuantumTrader-AI" >> flight_report.txt
          echo "📅 Date: $(date -u)" >> flight_report.txt
          echo "--------------------------------------" >> flight_report.txt
          echo "" >> flight_report.txt
          echo "🌍 Recent commits:" >> flight_report.txt
          git log -3 --pretty=format:"%h - %an, %ar : %s" >> flight_report.txt
          echo "" >> flight_report.txt
          echo "🧠 Sync status:" >> flight_report.txt
          echo "  QonexAI sync successful (15-min bidirectional link active)" >> flight_report.txt
          echo "" >> flight_report.txt
          echo "✅ All systems nominal. Preparing for November 2 test flight." >> flight_report.txt

      - name: Send Flight Report via Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✈️ QonexAI Daily Flight Log — $(date)"
          to: "ajibulurobotman@gmail.com"
          from: "QonexAI Mission Control <${{ secrets.EMAIL_USER }}>"
          secure: true
          body: "Automated daily report from QuantumTrader AI / QonexAI Mission Control"
          attachments: flight_report.txt
