name: 🧭 QT AI Mode Switch & Flight Control

on:
  schedule:
    - cron: "0 0 * * *"   # Runs once daily at midnight UTC
  workflow_dispatch:        # Allow manual run

jobs:
  mode_switch:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🔍 Determine Current Mode
        id: modecheck
        run: |
          TODAY=$(date +'%Y-%m-%d')
          TESTDATE="2025-11-02"
          FINALDATE="2025-11-09"
          echo "Today: $TODAY"
          if [[ "$TODAY" < "$TESTDATE" ]]; then
            MODE="PREPARATION"
          elif [[ "$TODAY" == "$TESTDATE" ]]; then
            MODE="TEST_FLIGHT"
          elif [[ "$TODAY" > "$TESTDATE" && "$TODAY" < "$FINALDATE" ]]; then
            MODE="TEST_FLIGHT_PHASE"
          elif [[ "$TODAY" == "$FINALDATE" || "$TODAY" > "$FINALDATE" ]]; then
            MODE="FULL_ROLLOUT"
          fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT

      - name: 🧠 Log Current Mode
        run: |
          mkdir -p logs
          echo "$(date): Mode set to ${{ steps.modecheck.outputs.mode }}" >> logs/mode-switch.log
          cat logs/mode-switch.log

      - name: 📨 Email Mode Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🧭 QT AI Mode Update — ${{ steps.modecheck.outputs.mode }}"
          to: ajibulurobotman@gmail.com
          from: "QuantumTrader AI Control <${{ secrets.EMAIL_USER }}>"
          secure: true
          body: |
            Hello Olagoke Ajibulu,

            QuantumTrader AI has automatically updated its operational mode:

            🧠 **Current Mode:** ${{ steps.modecheck.outputs.mode }}

            System time (UTC): $(date)

            — QT AI Flight Control
